// Equipment versions, batch 1 (Sep 2026): node tools/research.cjs variants tools/variants/batch-1.cjs [id...]
const each = (ex, f) => { ex.keyframes.forEach((k, i) => f(k.pose, k, i)); return ex; };
const torsoOf = p => (p.torso ? p.torso[0] : 0);
// arms hanging straight down with a weight in each hand (out a little from the thighs)
const hang = (p, out = 8) => { const t = torsoOf(p); p.shoulderL = [t, out, 0]; p.shoulderR = [t, out, 0]; delete p.elbowL; delete p.elbowR; };
const DB2 = axis => [{ type: 'dumbbell', hand: 'handL', axis }, { type: 'dumbbell', hand: 'handR', axis }];
module.exports = [
  { id: 'fw-db-squat', base: 'bw-squat', name: 'Dumbbell Squat', otherNames: ['Dumbbell Bodyweight-Style Squat'].slice(0, 0),
    equipment: ['Dumbbells'], collections: ['Free weights'], props: DB2('fb'),
    edit: ex => each(ex, p => hang(p)),
    description: 'A squat holding a dumbbell in each hand at your sides: sit your hips back and down, then stand up tall.',
    setup: ['Stand with feet hip-width apart.', 'Hold a dumbbell in each hand, arms hanging at your sides, palms facing in.'],
    cues: ['Sit your hips back and bend your knees.', 'Chest up, arms hang straight.', 'Push through your heels to stand.'],
    steps: [['Stand tall', 'Dumbbells at your sides.'], ['Squat down', 'Sit back and down, arms hanging.']],
    source: { url: 'https://www.acefitness.org/resources/everyone/exercise-library/equipment/dumbbells/', title: 'ACE Exercise Library: dumbbell exercises' } },
  { id: 'fw-db-reverse-lunge', base: 'bw-reverse-lunge', name: 'Dumbbell Reverse Lunge', otherNames: ['Dumbbell Rear Lunge'],
    equipment: ['Dumbbells'], collections: ['Free weights'], props: DB2('fb'),
    edit: ex => each(ex, p => hang(p, 6)),
    description: 'A reverse lunge holding a dumbbell in each hand: step one foot back, lower until both knees bend to about 90°, then step back in.',
    setup: ['Stand tall with feet hip-width apart.', 'Hold a dumbbell in each hand at your sides.'],
    cues: ['Step back onto the ball of your foot.', 'Lower straight down, chest tall.', 'Push through the front heel to come back.'],
    steps: [['Stand tall', 'Dumbbells at your sides.'], [null, 'Shift onto your left leg and lift your right foot.'], [null, 'Step back and bend both knees, arms hanging.'], [null, 'Drive through your front heel and step back in.']],
    source: { url: 'https://www.muscleandstrength.com/exercises/dumbbell-rear-lunge.html', title: 'Muscle & Strength: Dumbbell Rear Lunge' } },
  { id: 'fw-db-step-up', base: 'step-up', name: 'Dumbbell Step-Up',
    equipment: ['Step', 'Dumbbells'], collections: ['Free weights'], props: p => [...p, ...DB2('fb')],
    edit: ex => each(ex, p => hang(p, 6)),
    description: 'A step-up holding a dumbbell in each hand: step up onto a sturdy step, stand tall on it, then step back down.',
    setup: ['Stand facing a sturdy step or low box.', 'Hold a dumbbell in each hand at your sides.'],
    cues: ['Whole foot on the step.', 'Push through that heel to stand up.', 'Step down with control.'],
    steps: [['Stand in front of the step', 'Dumbbells at your sides.'], [null, 'Place your right foot flat on the step.'], [null, 'Push up and bring your left foot onto the step.'], [null, 'Step your right foot back down to the floor.']],
    source: { url: 'https://www.muscleandstrength.com/exercises/dumbbell-step-up.html', title: 'Muscle & Strength: Dumbbell Step Up' } },
  { id: 'fw-db-calf-raise', base: 'calf-raise', name: 'Dumbbell Calf Raise', otherNames: ['Standing Dumbbell Calf Raise'],
    equipment: ['Dumbbells'], collections: ['Free weights'], props: () => DB2('fb'),
    edit: ex => each(ex, (p, k) => { hang(p, 6); delete k.keep; }),
    description: 'A calf raise holding a dumbbell in each hand: rise up onto the balls of your feet, pause, and lower your heels slowly.',
    setup: ['Stand tall with feet hip-width apart.', 'Hold a dumbbell in each hand at your sides.'],
    cues: ['Rise onto the balls of your feet.', 'Knees straight, body tall.', 'Lower your heels slowly.'],
    steps: [['Stand tall', 'Feet flat, dumbbells at your sides.'], [null, 'Rise onto the balls of your feet.']],
    prescription: { reps: '10–15', note: 'Pick weights you can hold for every rep. Rise and lower slowly, without bouncing.' },
    source: { url: 'https://exrx.net/WeightExercises/Gastrocnemius/DBStandingCalfRaise', title: 'ExRx: Dumbbell Standing Calf Raise' } },
  { id: 'chair-calf-raise', base: 'calf-raise', name: 'Chair-Supported Calf Raise', otherNames: ['Calf Raise Holding a Chair'],
    equipment: ['Chair'], collections: ['Chair-based'], props: () => [{ type: 'chair', back: 'behind', z: 78 }],
    edit: ex => each(ex, (p, k) => { k.reach = [{ hand: 'handL', to: 'chair' }, { hand: 'handR', to: 'chair' }]; delete k.keep; delete p.shoulderL; delete p.shoulderR; delete p.elbowL; delete p.elbowR; }),
    description: 'A calf raise holding the back of a sturdy chair for balance: rise onto the balls of your feet and lower slowly.',
    setup: ['Stand behind a sturdy chair, feet hip-width apart.', 'Rest your hands lightly on the chair back.'],
    cues: ['Rise onto the balls of your feet.', 'Hold the chair lightly, just for balance.', 'Lower your heels slowly.'],
    steps: [['Stand tall', 'Feet flat, hands on the chair.'], [null, 'Rise onto the balls of your feet.']],
    prescription: { reps: '10–15', note: 'Hold the chair only for balance. Rise and lower slowly.' },
    source: { url: 'https://www.nhs.uk/live-well/exercise/strength-exercises/', title: 'NHS: Strength exercises' } },
  { id: 'fw-kb-deadlift', base: 'fw-bb-deadlift', name: 'Kettlebell Deadlift',
    equipment: ['Kettlebell'], collections: ['Free weights'], props: () => [{ type: 'kettlebell', hands: ['handL', 'handR'] }],
    edit: ex => each(ex, (p, k) => { for (const s of ['L', 'R']) p['shoulder' + s] = [p['shoulder' + s][0], -12, 0]; }),
    description: 'A hip hinge lifting one kettlebell from between your feet: push your hips back, grip the handle with both hands, and stand up tall.',
    setup: ['Stand with feet a little wider than hip-width, the kettlebell on the floor between them.', 'Hinge down and hold the handle with both hands.'],
    cues: ['Hips back, back flat.', 'Drive through your feet and stand tall.', 'Squeeze your glutes at the top.'],
    steps: [['Set up', 'Hips back, both hands on the handle.'], ['Stand up', 'Stand tall and squeeze your glutes.']],
    source: { url: 'https://www.nasm.org/resource-center/exercise-library/kettlebell-deadlift', title: 'NASM Exercise Library: Kettlebell Deadlift' } },
  { id: 'fw-bb-rdl', base: 'fw-db-rdl', name: 'Barbell Romanian Deadlift', otherNames: ['Barbell RDL'],
    equipment: ['Barbell'], collections: ['Free weights'], props: () => [{ type: 'barbell', from: 'handL', to: 'handR' }],
    edit: ex => ex,
    description: 'A hip hinge with a barbell held in front of your thighs: push your hips back with soft knees until you feel the hamstrings stretch, then stand up.',
    setup: ['Stand with feet hip-width apart, the barbell held at your thighs, hands just outside your legs.'],
    cues: ['Push your hips back, knees soft.', 'Keep the bar close to your legs.', 'Squeeze your glutes to stand.'],
    steps: [['Stand tall', 'Bar in front of your thighs.'], [null, 'Push your hips back and slide the bar down your legs.']],
    source: { url: 'https://www.nasm.org/resource-center/exercise-library/romanian-deadlift-barbell', title: 'NASM Exercise Library: Romanian Deadlift (Barbell)' } },
  { id: 'fw-bb-row', base: 'fw-db-row', name: 'Barbell Bent-Over Row', otherNames: ['Barbell Row', 'Bent-Over Row'],
    equipment: ['Barbell'], collections: ['Free weights'], props: () => [{ type: 'barbell', from: 'handL', to: 'handR' }],
    edit: ex => ex,
    description: 'Hinged forward with a flat back, pull a barbell up toward the bottom of your ribs, squeezing your shoulder blades, then lower it.',
    setup: ['Hold the barbell with an overhand grip a little wider than your shoulders.', 'Soft knees, hinge forward with a flat back.'],
    cues: ['Pull the bar to your lower ribs.', 'Elbows close, squeeze your shoulder blades.', 'Lower with control.'],
    steps: [['Bar hanging', 'Hinged forward, back flat.'], [null, 'Pull the bar to your lower ribs.']],
    source: { url: 'https://www.acefitness.org/resources/everyone/exercise-library/12/bent-over-row/', title: 'ACE Exercise Library: Bent-Over Row' } },
  { id: 'fw-bb-curl', base: 'fw-db-curl', name: 'Barbell Curl', otherNames: ['Barbell Bicep Curl'],
    equipment: ['Barbell'], collections: ['Free weights'], props: () => [{ type: 'barbell', from: 'handL', to: 'handR' }],
    edit: ex => ex,
    description: 'A biceps curl with a barbell: holding it with palms up at shoulder width, bend your elbows to lift it toward your shoulders, then lower it slowly.',
    setup: ['Stand tall and hold the barbell with palms facing forward, hands shoulder-width apart.'],
    cues: ['Elbows stay by your sides.', 'Curl the bar up without swinging.', 'Lower it slowly.'],
    steps: [['Arms down', 'Bar in front of your thighs, palms forward.'], [null, 'Bend your elbows to bring the bar to your shoulders.']],
    prescription: { reps: '8–12', note: 'Pick a weight you can lift for every rep without swinging. About 2 seconds up and 2 seconds down.' },
    source: { url: 'https://www.muscleandstrength.com/exercises/standing-barbell-curl.html', title: 'Muscle & Strength: Standing Barbell Curl' } },
  { id: 'fw-kb-goblet-squat', base: 'fw-goblet-squat', name: 'Kettlebell Goblet Squat',
    equipment: ['Kettlebell'], collections: ['Free weights'], props: () => [{ type: 'kettlebell', hands: ['handL', 'handR'] }],
    edit: ex => ex,
    description: 'A squat holding one kettlebell close to your chest by its handle: sit your hips down between your heels, then stand up.',
    setup: ['Stand with feet about shoulder-width apart.', 'Hold the kettlebell by the handle at your chest, elbows tucked in.'],
    cues: ['Elbows in, chest up.', 'Sit down between your heels.', 'Push through your heels to stand.'],
    steps: [['Stand tall', 'Kettlebell at your chest.'], [null, 'Sit down between your heels.']],
    source: { url: 'https://www.muscleandstrength.com/exercises/kettlebell-goblet-squat', title: 'Muscle & Strength: Kettlebell Goblet Squat' } },
  { id: 'band-glute-bridge', base: 'bw-glute-bridge', name: 'Banded Glute Bridge', otherNames: ['Resistance Band Glute Bridge'],
    equipment: ['Resistance band'], collections: ['Resistance band'], props: () => [{ type: 'band', from: 'kneeL', to: 'kneeR' }],
    edit: ex => each(ex, p => { p.hipL = [p.hipL[0], 8, 0]; p.hipR = [p.hipR[0], 8, 0]; }),
    description: 'A glute bridge with a loop band just above your knees: press your knees out against the band as you lift your hips.',
    setup: ['Lie on your back, knees bent, feet flat and hip-width apart.', 'Put a loop band just above your knees.'],
    cues: ['Press your knees out against the band.', 'Lift your hips until shoulders, hips and knees line up.', 'Lower slowly.'],
    steps: [[null, 'Knees bent, band above your knees.'], [null, 'Press your knees out and lift your hips.']],
    prescription: { reps: '10–15', note: 'Keep pressing out against the band the whole time. About 2 seconds up and 2 seconds down.' },
    source: { url: 'https://www.muscleandstrength.com/exercises/banded-glute-bridge', title: 'Muscle & Strength: Banded Glute Bridge' } },
  { id: 'band-clamshell', base: 'side-clamshell', name: 'Banded Clamshell', otherNames: ['Resistance Band Clamshell'],
    equipment: ['Resistance band'], collections: ['Resistance band'], props: () => [{ type: 'band', from: 'kneeL', to: 'kneeR' }],
    edit: ex => ex,
    description: 'The clamshell with a loop band just above your knees: lying on your side with feet together, open the top knee against the band.',
    setup: ['Lie on your side, knees bent and stacked, feet together.', 'Put a loop band just above your knees.'],
    cues: ['Keep your feet together.', 'Open the top knee without rolling back.', 'Close slowly.'],
    prescription: { reps: '12–15 each leg', note: 'A light band is plenty. Move slowly and keep your hips still.' },
    source: { url: 'https://blog.nasm.org/banded-clamshell-workout', title: 'NASM: The Banded Clamshell' } },
  { id: 'band-standing-kickback', base: 'bw-leg-extension', name: 'Banded Standing Kickback', otherNames: ['Resistance Band Glute Kickback', 'Banded Standing Hip Extension'],
    equipment: ['Resistance band', 'Chair'], collections: ['Resistance band'], props: p => [...p, { type: 'band', from: 'ankleL', to: 'ankleR' }],
    edit: ex => ex,
    description: 'Holding a chair for balance with a loop band around your ankles, kick one straight leg back against the band, then bring it back.',
    setup: ['Stand behind a sturdy chair, hands on its back.', 'Put a loop band around your ankles.'],
    cues: ['Kick the leg straight back.', 'Squeeze your glute, don\'t arch your back.', 'Bring it back slowly.'],
    steps: [['Stand tall', 'Hands on the chair, band around your ankles.'], ['Kick back', 'Kick your right leg straight back.']],
    prescription: { reps: '10–15 each leg', note: 'A light loop band. Move slowly and keep your back still.' },
    source: { url: 'https://fitbod.me/blog/banded-kickback-variations/', title: 'Fitbod: Banded kickback variations' } },
  { id: 'band-bent-over-row', base: 'fw-db-row', name: 'Resistance Band Bent-Over Row', otherNames: ['Band Bent-Over Row'],
    equipment: ['Resistance band'], collections: ['Resistance band'], props: () => [{ type: 'band', from: 'footL', to: 'handL' }, { type: 'band', from: 'footR', to: 'handR' }],
    edit: ex => ex,
    description: 'Standing on the middle of a band and hinged forward with a flat back, pull the ends toward your lower ribs, then lower them.',
    setup: ['Stand on the middle of the band, feet shoulder-width apart, holding an end in each hand.', 'Soft knees, hinge forward with a flat back.'],
    cues: ['Pull the ends to your lower ribs.', 'Elbows close, squeeze your shoulder blades.', 'Lower with control.'],
    steps: [['Arms hanging', 'Hinged forward, standing on the band.'], [null, 'Pull the band to your lower ribs.']],
    prescription: { reps: '10–15', note: 'Pick a band you can pull for every rep with good form. About 2 seconds to pull and 2 seconds to lower.' },
    source: { url: 'https://workoutlabs.com/exercise-guide/resistance-band-bent-over-rows/', title: 'WorkoutLabs: Resistance Band Bent Over Rows' } },
  { id: 'band-triceps-kickback', base: 'fw-db-kickback', name: 'Resistance Band Triceps Kickback', otherNames: ['Band Triceps Kickback'],
    equipment: ['Resistance band'], collections: ['Resistance band'], props: () => [{ type: 'band', from: 'footL', to: 'handL' }, { type: 'band', from: 'footR', to: 'handR' }],
    edit: ex => ex,
    description: 'Standing on a band and hinged forward, elbows tucked at your sides, straighten your arms back against the band, then bend them again.',
    setup: ['Stand on the middle of the band, holding an end in each hand.', 'Hinge forward, elbows bent and tucked to your sides.'],
    cues: ['Upper arms stay still.', 'Straighten your arms back.', 'Bend them slowly.'],
    steps: [[null, 'Upper arms by your sides, standing on the band.'], [null, 'Straighten your arms behind you.']],
    prescription: { reps: '10–15', note: 'Pick a band you can straighten your arms against for every rep. About 2 seconds each way.' },
    source: { url: 'https://workoutlabs.com/exercise-guide/resistance-band-tricep-kickbacks/', title: 'WorkoutLabs: Resistance Band Tricep Kickbacks' } },
  { id: 'fw-db-overhead-triceps', base: 'band-overhead-triceps', name: 'Dumbbell Overhead Triceps Extension', otherNames: ['Two-Arm Dumbbell Overhead Extension'],
    equipment: ['Dumbbell'], collections: ['Free weights'], props: () => [{ type: 'dumbbell', hand: 'handR', axis: 'ud' }],
    edit: ex => each(ex, p => { p.shoulderL = [p.shoulderL[0], -6, 0]; p.shoulderR = [p.shoulderR[0], -6, 0]; }),
    description: 'Holding one dumbbell overhead with both hands, bend your elbows to lower it behind your head, then straighten your arms.',
    setup: ['Stand with feet shoulder-width apart.', 'Hold one dumbbell overhead with both hands around the handle.'],
    cues: ['Elbows point up, close to your head.', 'Lower the weight behind your head.', 'Straighten your arms.'],
    steps: [['Weight behind your head', 'Elbows up, both hands on the dumbbell.'], [null, 'Straighten your arms overhead.']],
    source: { url: 'https://www.acefitness.org/resources/everyone/exercise-library/74/triceps-extension/', title: 'ACE Exercise Library: Triceps Extension' } },
  { id: 'bench-dip', base: 'chair-dip', name: 'Bench Dip', otherNames: ['Triceps Bench Dip'],
    equipment: ['Bench'], collections: ['Bodyweight'], props: () => [{ type: 'bench', z: -60, width: 70, depth: 200, height: 80 }],
    edit: ex => ex,
    description: 'Hands on the edge of a bench behind you and feet on the floor, bend your elbows to lower your hips, then press back up.',
    setup: ['Sit on the edge of a bench, hands beside your hips, fingers forward.', 'Walk your feet out and lift your hips off the bench.'],
    cues: ['Keep your back close to the bench.', 'Lower until your elbows are at about 90°.', 'Press back up.'],
    steps: [[null, 'Hips just in front of the bench, arms straight.'], [null, 'Bend your elbows and lower your hips.']],
    source: { url: 'https://www.nasm.org/resource-center/exercise-library/bench-dips', title: 'NASM Exercise Library: Bench Dips' } },
  { id: 'bw-good-morning', base: 'fw-db-rdl', name: 'Bodyweight Good Morning', otherNames: ['Good Morning'],
    equipment: [], collections: ['Bodyweight'], props: () => [],
    edit: ex => each(ex, p => { p.shoulderL = [150, 40, 0]; p.shoulderR = [150, 40, 0]; p.elbowL = 150; p.elbowR = 150; }),
    description: 'A hip hinge with no weight, hands behind your head: push your hips back with soft knees until your hamstrings stretch, then stand up.',
    setup: ['Stand with feet hip-width apart, knees soft.', 'Hands lightly behind your head, elbows wide.'],
    cues: ['Push your hips back.', 'Back flat, chest proud.', 'Squeeze your glutes to stand.'],
    steps: [['Stand tall', 'Hands behind your head, knees soft.'], [null, 'Push your hips back, back flat.']],
    prescription: { reps: '10–15', note: 'Only go as far as your back stays flat. About 2 seconds down and 2 seconds up.' },
    source: { url: 'https://www.issaonline.com/blogs/training-tips/how-to-do-the-good-morning-exercise-and-why-you-should', title: 'ISSA: How to do the good morning exercise' } },
];
