// Collection research, batch 3: common yoga poses the library didn't have (docs/collection-research.md).
// node tools/research.cjs variants tools/variants/batch-3-yoga.cjs [id...]
const K = (name, cue, pose, x = {}) => ({ name, cue, camera: 90, durationMs: 2000, holdMs: 1000, phase: 'setup', ...x, pose });
const HOLD = { phase: 'rep', durationMs: 2600, holdMs: 5000 };
const MAT = ['Yoga mat'];
const hold = (s = 30) => ({ measure: 'time', holdStep: 1, defaults: { seconds: s }, repName: null, prescription: { reps: `hold ${s} seconds`, note: 'Breathe slowly and evenly; come out of the pose if anything pinches.' } });
const sides = { bilateral: { labels: { L: 'Left side', R: 'Right side' } } };
const YJ = (slug, title) => ({ url: `https://www.yogajournal.com/poses/${slug}/`, title: `Yoga Journal: ${title}` });
// shared starting positions
const PRONE = K('Lie on your belly', 'Lie face down, arms by your sides.', { root: [90, 0, 0], neck: [-34, 0, 0], ankleL: 90, ankleR: 90 }, { anchor: 'pelvis' });
const MOUNTAIN = K('Mountain Pose', 'Stand tall, feet together.', {}, { anchor: 'ankleR', plant: ['L', 'R'] });
const SUPINE = K('Lie on your back', 'Lie down, knees bent, feet flat.', { root: [-90, 0, 0], neck: [34, 0, 0], hipL: [45, 0, 0], kneeL: 90, ankleL: 45, hipR: [45, 0, 0], kneeR: 90, ankleR: 45 },
  { anchor: 'neckBase', plant: ['L', 'R'], touch: [{ point: 'ankleR', adjust: 'kneeR' }, { point: 'ankleL', adjust: 'kneeL' }] });
const KNEEL = K('Tabletop', 'Hands under shoulders, knees under hips.', { root: [75, 0, 0], shoulderL: [75, 0, 0], shoulderR: [75, 0, 0], hipL: [75, 0, 0], kneeL: 90, ankleL: 90, hipR: [75, 0, 0], kneeR: 90, ankleR: 90 },
  { anchor: 'handR', touch: [{ point: 'kneeR', adjust: 'hipR' }, { point: 'kneeL', adjust: 'hipL' }] });
const pose = (id, name, sanskrit, others, extra) => ({ id, base: 'yoga-locust', name, otherNames: [sanskrit, ...others], equipment: MAT, collections: ['Yoga'], ...extra,
  over: { ...(extra.bilateral ? sides : { bilateral: null }), ...hold(extra.seconds || 30), ...(extra.over || {}) } });
module.exports = [
  pose('yoga-cobra', 'Cobra Pose', 'Bhujangasana', ['Cobra'], { category: 'Backbend', focus: 'Spine and chest',
    edit: ex => { ex.keyframes = [PRONE, K('Cobra Pose', 'Press into your hands and lift your chest, hips down.',
      { root: [90, 0, 0], torso: [-30, 0, 0], chest: [-10, 0, 0], neck: [-10, 0, 0], shoulderL: [-10, 0, 0], elbowL: 60, shoulderR: [-10, 0, 0], elbowR: 60, ankleL: 90, ankleR: 90 },
      { ...HOLD, anchor: 'pelvis', touch: [{ point: 'handR', adjust: 'shoulderR' }, { point: 'handL', adjust: 'shoulderL' }] })]; },
    description: 'A gentle backbend lying face down: with hands under your shoulders, lift your chest while your hips and legs stay on the floor.',
    setup: ['Lie face down, legs long, tops of the feet on the mat.', 'Place your hands flat under your shoulders, elbows hugging your sides.'],
    cues: ['Lift with your back, not just your arms.', 'Shoulders away from your ears.', 'Keep your hips down.'], source: YJ('cobra-pose', 'Cobra Pose') }),
  pose('yoga-sphinx', 'Sphinx Pose', 'Salamba Bhujangasana', [], { category: 'Backbend', focus: 'Lower back and chest',
    edit: ex => { ex.keyframes = [K('Lie on your belly', 'Lie face down, arms reaching forward along the mat.', { root: [90, 0, 0], neck: [-34, 0, 0], shoulderL: [180, 0, 0], shoulderR: [180, 0, 0], ankleL: 90, ankleR: 90 }, { anchor: 'pelvis' }), K('Forearms down', 'Slide your forearms forward, elbows under your shoulders.', { root: [90, 0, 0], torso: [-18, 0, 0], neck: [-10, 0, 0], shoulderL: [140, 0, 0], elbowL: 30, shoulderR: [140, 0, 0], elbowR: 30, ankleL: 90, ankleR: 90 }, { anchor: 'pelvis' }), K('Sphinx Pose', 'Forearms down, elbows under your shoulders, chest up.',
      { root: [90, 0, 0], torso: [-36, 0, 0], neck: [6, 0, 0], shoulderL: [54, 0, 0], elbowL: 90, shoulderR: [54, 0, 0], elbowR: 90, ankleL: 90, ankleR: 90 },
      { ...HOLD, anchor: 'pelvis' })]; },
    description: 'A gentle backbend on your forearms: lying face down with elbows under your shoulders, lift your chest and look ahead.',
    over: { holdStep: 2 },
    setup: ['Lie face down, legs long.', 'Forearms on the mat, elbows under your shoulders.'],
    cues: ['Press your forearms down.', 'Lengthen your tailbone toward your heels.', 'Neck long, gaze ahead.'], source: YJ('sphinx-pose', 'Sphinx Pose') }),
  pose('yoga-low-lunge', 'Low Lunge', 'Anjaneyasana', ['Crescent Moon Pose'], { category: 'Hip opener', focus: 'Hip flexors and thighs', bilateral: true,
    edit: ex => { ex.keyframes = [MOUNTAIN, K('Low Lunge', 'Right foot forward, left knee down, arms up.',
      { shoulderL: [-180, 0, 0], shoulderR: [-180, 0, 0], hipR: [100, 0, 0], kneeR: 100, hipL: [-35, 0, 0], kneeL: 60, ankleL: 60 },
      { ...HOLD, anchor: 'ankleR', plant: ['R'], touch: [{ point: 'kneeL', adjust: 'hipL' }] })]; },
    description: 'A lunge with the back knee on the floor: front knee over the ankle, hips sinking forward, arms reaching up.',
    setup: ['Kneel, then step your right foot forward so the knee is over the ankle.', 'Pad the back knee if it\'s tender.'],
    cues: ['Sink your hips forward and down.', 'Front knee over the ankle.', 'Reach up through your fingertips.'], source: YJ('low-lunge', 'Low Lunge') }),
  pose('yoga-crescent-lunge', 'Crescent Lunge', 'Ashta Chandrasana', ['High Lunge'], { category: 'Standing', focus: 'Legs and hip flexors', bilateral: true,
    edit: ex => { ex.keyframes = [MOUNTAIN, K('Crescent Lunge', 'Right knee bent, back heel lifted, arms up.',
      { shoulderL: [-180, 0, 0], shoulderR: [-180, 0, 0], hipR: [85, 0, 0], kneeR: 90, hipL: [-40, 0, 0], kneeL: 12, ankleL: 30 },
      { ...HOLD, anchor: 'ankleR', plant: ['R'], touch: [{ point: 'toeL', adjust: 'hipL' }] })]; },
    description: 'A high lunge on the ball of the back foot: front knee bent over the ankle, back leg long, arms reaching up.',
    setup: ['From standing, step your left foot back and rise onto its ball.'],
    cues: ['Front knee over the ankle.', 'Back leg strong and long.', 'Ribs down as your arms reach up.'], source: YJ('high-lunge-crescent-variation', 'High Lunge, Crescent Variation') }),
  pose('yoga-lizard', 'Lizard Pose', 'Utthan Pristhasana', ['Lizard Lunge'], { category: 'Hip opener', focus: 'Hips and hip flexors', bilateral: true,
    edit: ex => { ex.keyframes = [MOUNTAIN, K('Lizard Pose', 'Right foot forward, hands inside it, back knee down.',
      { torso: [60, 0, 0], neck: [-20, 0, 0], shoulderL: [30, 0, 0], shoulderR: [30, 0, 0], hipR: [110, 20, 20], kneeR: 110, hipL: [-35, 0, 0], kneeL: 60, ankleL: 60 },
      { ...HOLD, anchor: 'ankleR', plant: ['R'], touch: [{ point: 'kneeL', adjust: 'hipL' }, { point: 'handR', adjust: 'shoulderR' }, { point: 'handL', adjust: 'shoulderL' }] })]; },
    description: 'A deep lunge with both hands inside the front foot: back knee down, hips sinking low to open the hips.',
    setup: ['From a low lunge with the right foot forward, bring both hands inside the right foot.'],
    cues: ['Let your hips sink.', 'Chest long, not collapsing.', 'Come onto the forearms only if it\'s easy.'], source: YJ('lizard-pose', 'Lizard Pose') }),
  pose('yoga-reverse-warrior', 'Reverse Warrior', 'Viparita Virabhadrasana', ['Peaceful Warrior'], { category: 'Standing', focus: 'Legs and side body', bilateral: true,
    edit: ex => { ex.keyframes = [K('Warrior 2', 'Right knee bent, arms wide.',
      { shoulderL: [0, 90, 0], shoulderR: [0, 90, 0], hipL: [0, 60, 0], hipR: [0, 90, 90], kneeR: 90 },
      { camera: 0, anchor: 'ankleR', plant: ['L', 'R'], touch: [{ point: 'ankleL', adjust: 'hipL.side' }] }),
      K('Reverse Warrior', 'Right arm up and back, left hand slides down the back leg.',
      { torso: [0, -18, 0], chest: [0, -12, 0], neck: [0, -8, 0], shoulderL: [0, 20, 0], shoulderR: [0, 160, 0], hipL: [0, 60, 0], hipR: [0, 90, 90], kneeR: 90 },
      { ...HOLD, camera: 0, anchor: 'ankleR', plant: ['L', 'R'], touch: [{ point: 'ankleL', adjust: 'hipL.side' }] })]; },
    description: 'From Warrior 2, keep the front knee bent and arc the front arm up and back while the back hand rests on the back leg.',
    setup: ['Start in Warrior 2 with the right knee bent.'],
    cues: ['Keep the front knee over the ankle.', 'Lift through the side body, don\'t sink into the back hand.', 'Breathe into your ribs.'], source: YJ('reverse-warrior', 'Reverse Warrior') }),
  pose('yoga-humble-warrior', 'Humble Warrior', 'Baddha Virabhadrasana', ['Bound Warrior'], { category: 'Standing', focus: 'Legs, hips and shoulders', bilateral: true,
    edit: ex => { ex.keyframes = [MOUNTAIN, K('Humble Warrior', 'Hands clasped behind you, bow inside the right knee.',
      { torso: [70, 0, 0], neck: [10, 0, 0], shoulderL: [-70, -10, 0], shoulderR: [-70, -10, 0], hipL: [-60, 0, 0], ankleL: -60, hipR: [90, 10, 0], kneeR: 90 },
      { ...HOLD, anchor: 'ankleR', plant: ['L', 'R'], touch: [{ point: 'ankleL', adjust: 'hipL' }] })]; },
    description: 'From a Warrior 1 stance, clasp your hands behind your back and fold the chest inside the front knee, arms lifting away from your back.',
    setup: ['Start in Warrior 1 with the right foot forward.', 'Interlace your fingers behind your back.'],
    cues: ['Bow inside the front knee.', 'Let your arms lift away from your back.', 'Keep the back heel down.'], source: YJ('humble-warrior', 'Humble Warrior') }),
  pose('yoga-goddess', 'Goddess Pose', 'Utkata Konasana', ['Horse Stance'], { category: 'Standing', focus: 'Thighs and inner legs',
    edit: ex => { ex.keyframes = [K('Step wide', 'Feet wide, toes turned out.', { hipL: [0, 30, 45], hipR: [0, 30, 45] }, { camera: 0, anchor: 'ankleR', plant: ['L', 'R'], touch: [{ point: 'ankleL', adjust: 'hipL.side' }] }),
      K('Goddess Pose', 'Bend your knees wide, arms up like a cactus.',
      { shoulderL: [0, 90, -90], elbowL: 90, shoulderR: [0, 90, -90], elbowR: 90, hipL: [0, 70, 90], kneeL: 90, hipR: [0, 70, 90], kneeR: 90 },
      { ...HOLD, camera: 0, anchor: 'ankleR', plant: ['L', 'R'], touch: [{ point: 'ankleL', adjust: 'hipL.side' }] })]; },
    description: 'A wide-legged squat with the toes turned out: sink the hips until the knees bend over the ankles, arms bent up like a cactus.',
    setup: ['Stand with your feet wide apart, toes turned out.'],
    cues: ['Knees track over your toes.', 'Tailbone down, chest lifted.', 'Elbows at shoulder height.'], source: YJ('goddess-pose', 'Goddess Pose') }),
  pose('yoga-happy-baby', 'Happy Baby Pose', 'Ananda Balasana', ['Happy Baby'], { category: 'Hip opener', focus: 'Hips and lower back',
    edit: ex => { ex.keyframes = [SUPINE, K('Happy Baby Pose', 'Knees toward your armpits, hold the outsides of your feet.',
      { root: [-90, 0, 0], neck: [34, 0, 0], hipL: [160, 15, 0], kneeL: 70, ankleL: -10, hipR: [160, 15, 0], kneeR: 70, ankleR: -10 },
      { ...HOLD, anchor: 'neckBase', reach: [{ hand: 'handR', to: 'footR' }, { hand: 'handL', to: 'footL' }] })]; },
    description: 'Lying on your back, draw your knees toward your armpits and hold the outsides of your feet, soles toward the ceiling.',
    setup: ['Lie on your back and bring your knees toward your chest.'],
    cues: ['Soles face the ceiling.', 'Gently draw your knees down toward the floor.', 'Back of your head stays down.'], source: YJ('happy-baby-pose', 'Happy Baby Pose') }),
  pose('yoga-garland', 'Garland Pose', 'Malasana', ['Yogi Squat', 'Deep Squat'], { category: 'Hip opener', focus: 'Hips, ankles and groin',
    edit: ex => { ex.keyframes = [MOUNTAIN, K('Garland Pose', 'Squat deep, heels down, elbows inside your knees.',
      { torso: [30, 0, 0], shoulderL: [20, 10, 0], elbowL: 120, shoulderR: [20, 10, 0], elbowR: 120, hipL: [115, 30, 30], kneeL: 140, ankleL: -35, hipR: [115, 30, 30], kneeR: 140, ankleR: -35 },
      { ...HOLD, anchor: 'ankleR', plant: ['L', 'R'] })]; },
    description: 'A deep squat with heels down and knees wide: palms together at your chest, elbows pressing the knees open.',
    setup: ['Stand with your feet a little wider than your hips, toes turned out.'],
    cues: ['Heels down (a folded blanket under them helps).', 'Chest long.', 'Elbows press your knees open.'], source: YJ('garland-pose', 'Garland Pose') }),
  pose('yoga-puppy', 'Puppy Pose', 'Uttana Shishosana', ['Extended Puppy Pose'], { category: 'Stretch', focus: 'Shoulders and upper back',
    edit: ex => { ex.keyframes = [KNEEL, K('Puppy Pose', 'Hips over your knees, walk the hands forward, chest down.',
      { torso: [95, 0, 0], chest: [20, 0, 0], neck: [-10, 0, 0], shoulderL: [175, 0, 0], shoulderR: [175, 0, 0], kneeL: 90, ankleL: 90, kneeR: 90, ankleR: 90 },
      { ...HOLD, anchor: 'kneeR', touch: [{ point: 'headLow', adjust: 'torso' }, { point: 'handR', adjust: 'shoulderR' }, { point: 'handL', adjust: 'shoulderL' }] })]; },
    description: 'Between Child\'s Pose and Downward Dog: hips stay over the knees while the arms walk forward and the chest melts toward the floor.',
    setup: ['Start on hands and knees.'],
    cues: ['Hips over your knees.', 'Melt your chest down.', 'Arms long, elbows off the floor.'], source: YJ('extended-puppy-pose', 'Extended Puppy Pose') }),
  pose('yoga-fish', 'Fish Pose', 'Matsyasana', [], { category: 'Backbend', focus: 'Chest and throat',
    edit: ex => { ex.keyframes = [K('Lie on your back', 'Legs long, arms by your sides.', { root: [-90, 0, 0], neck: [34, 0, 0] }, { anchor: 'pelvis' }),
      K('Fish Pose', 'Lift your chest, crown of the head light on the floor.',
      // the chest arches up and over (Sep 2026: the neck alone bent 80° back), forearms flat under the hips, crown on the floor
      { root: [-90, 0, 0], torso: [40, 0, 0], chest: [-40, 0, 0], neck: [-30, 0, 0], shoulderL: [-35, 0, 0], shoulderR: [-35, 0, 0], elbowL: 35, elbowR: 35 },
      { ...HOLD, anchor: 'pelvis' })]; },
    description: 'A backbend lying on your back: lift your chest and let the crown of your head rest lightly on the floor, forearms flat beside you.',
    setup: ['Lie on your back, legs long, arms by your sides.'],
    cues: ['Press your forearms and elbows down to lift your chest.', 'Keep the weight off your head.', 'Legs stay active.'], source: YJ('fish-pose', 'Fish Pose') }),
  pose('yoga-reclined-bound-angle', 'Reclined Bound Angle Pose', 'Supta Baddha Konasana', ['Reclining Butterfly'], { category: 'Restorative', focus: 'Inner thighs and hips',
    edit: ex => { ex.keyframes = [SUPINE, K('Reclined Bound Angle Pose', 'Soles together, knees fall open, arms relaxed.',
      { root: [-90, 0, 0], neck: [34, 0, 0], shoulderL: [0, 40, 0], shoulderR: [0, 40, 0], hipL: [5, 60, 90], kneeL: 150, hipR: [5, 60, 90], kneeR: 150 },
      { ...HOLD, anchor: 'neckBase', camera: 25 })]; },
    description: 'Lying on your back with the soles of your feet together, let your knees fall open to the sides and rest.',
    setup: ['Lie on your back, knees bent, feet flat.'],
    cues: ['Soles together, knees drop open.', 'Support the knees with cushions if needed.', 'Let your belly soften.'], source: YJ('reclining-bound-angle-pose', 'Reclining Bound Angle Pose') }),
  pose('yoga-supine-twist', 'Supine Twist', 'Supta Matsyendrasana', ['Reclined Spinal Twist', 'Lying Spinal Twist'], { category: 'Twist', focus: 'Spine and outer hip', bilateral: true,
    // lying on the back spelled [-90, 90, 90] (the same as [-90, 0, 0], turned end for end), so the forward number rolls
    // the body onto its side: [-150, 90, 90] is a 60° roll onto the left hip; the chest turns back to keep the shoulders flat
    edit: ex => { ex.keyframes = [
      K('Lie on your back', 'Knees bent, feet flat, arms wide.', { root: [-90, 90, 90], neck: [34, 0, 0], shoulderL: [0, 80, 0], shoulderR: [0, 80, 0], hipL: [45, 0, 0], kneeL: 90, ankleL: 45, hipR: [45, 0, 0], kneeR: 90, ankleR: 45 },
        { anchor: 'neckBase', plant: ['L', 'R'], touch: [{ point: 'ankleR', adjust: 'kneeR' }, { point: 'ankleL', adjust: 'kneeL' }] }),
      K('Supine Twist', 'Right knee across to the left, shoulders down.',
      { root: [-135, 90, 90], torso: [0, 0, -45], neck: [34, 0, 0], shoulderL: [0, 80, 0], shoulderR: [0, 80, 0], hipR: [90, -40, 0], kneeR: 90 },
      { ...HOLD, anchor: 'backL' })]; },
    description: 'Lying on your back, draw one knee across your body toward the floor while your shoulders stay down and your arms reach wide.',
    setup: ['Lie on your back and hug your right knee in.'],
    cues: ['Both shoulders stay down.', 'Let gravity bring the knee down.', 'Breathe into the twist.'], source: YJ('reclining-twist', 'Reclined Twist') }),
];
